---
markdown: kramdown
kramdown:
  input: GFM
pygments: true
baseurl: "/sublimetext-markdown-slideshow"
encoding: UTF-8
exclude:
- README.md
- vendor
- tmp
name: Markdown Slideshow
copyright: 2014, ogom
theme: cosmo
